version: '3.8'

services:
  text-to-video:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PEXELS_KEY=${PEXELS_KEY}
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - VIDEO_ORIENTATION=${VIDEO_ORIENTATION:-landscape}
    volumes:
      - ./uploads:/app/uploads
      - ./.logs:/app/.logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    container_name: text-to-video-ai